various changes to prevent livelocks on update when docker is broken
adsb-docker: prevent it hogging the docker log in perpetuity

docker-compose-adsb: wait a max of 10 min for lock, exit if it can't be
acquired

diff --git a/src/modules/adsb-feeder/filesystem/root/opt/adsb/docker-compose-adsb b/src/modules/adsb-feeder/filesystem/root/opt/adsb/docker-compose-adsb
--- a/src/modules/adsb-feeder/filesystem/root/opt/adsb/docker-compose-adsb
+++ b/src/modules/adsb-feeder/filesystem/root/opt/adsb/docker-compose-adsb
@@ -38,8 +38,11 @@ exec 9>>"$lockFile"
 
 if ! flock --exclusive --nonblock 9; then
     echo "$(date -u +"%FT%T.%3NZ") $$: docker-compose-adsb will wait for lock"
-    flock --exclusive 9
-    echo "$(date -u +"%FT%T.%3NZ") $$: docker-compose-adsb finished waiting for lock"
+    if ! timeout 600 flock --exclusive 9; then
+        echo "$(date -u +"%FT%T.%3NZ") $$: docker-compose-adsb failed to get lock after 10 minutes, exiting"
+        exit 1
+    fi
+    echo "$(date -u +"%FT%T.%3NZ") $$: docker-compose-adsb acquired lock"
 fi
 
 docker_compose="docker compose"
