make the update script more robust
If a feeder update failed halfway through, I have seen situation where the
waiting-app still was running on the feeder port and that messed everything up.
This is much more careful about what is happening on the system.

Signed-off-by: Dirk Hohndel <dirk@hohndel.org>

diff --git a/src/modules/adsb-feeder/filesystem/root/opt/adsb/feeder-update b/src/modules/adsb-feeder/filesystem/root/opt/adsb/feeder-update
--- a/src/modules/adsb-feeder/filesystem/root/opt/adsb/feeder-update
+++ b/src/modules/adsb-feeder/filesystem/root/opt/adsb/feeder-update
@@ -1,7 +1,7 @@
 #!/bin/bash
 
 # this needs to run as root
-if [ $(id -u) != "0" ] ; then
+if [ "$(id -u)" != "0" ] ; then
 	echo "this command requires superuser privileges - please run as sudo bash $0"
 	exit 1
 fi
@@ -21,17 +21,39 @@ cleanup() {
 }
 
 waiting_placeholder() {
+    # make sure the waiting app isn't around anymore
+    if [ -f /opt/adsb-feeder-update/waiting-pid ] ; then kill "$(</opt/adsb-feeder-update/waiting-pid)" || true ; fi
+    rm -f /opt/adsb-feeder-update/waiting-pid
+
     PORT=$(grep _ADSBIM_STATE_WEBPORT /opt/adsb/config/.env | cut -d= -f2)
+    # figure out if something is listening to that port and give it some time to stop running
+    # this magic uses bash's /dev/tcp capability
+    for delay in 1 5 10 ; do
+        if timeout 1 bash -c "cat < /dev/null > /dev/tcp/127.0.0.1/$PORT" 2>/dev/null ; then
+            echo "There's still something running on port $PORT"
+            sleep $delay
+        else
+            break
+        fi
+    done
+    # finally start the waiting-app
     python3 /opt/adsb/adsb-setup/waiting-app.py "$PORT" &
-    mkdir -p /opt/adsb-feeder-update
-    echo $! > /opt/adsb-feeder-update/waiting-pid
+    PID="$!"
+    sleep 1
+    if kill -0 $PID ; then
+        # ok, the background process started
+        mkdir -p /opt/adsb-feeder-update
+        echo $! > /opt/adsb-feeder-update/waiting-pid
+    else
+        echo "Starting the waiting-app failed"
+    fi
 }
 
 # if this is an update where the previous version of the image used /var/log/adsb-setup.log
 # and this is the first time we use the new location, copy the existing log over
 [ ! -f /opt/adsb/adsb-setup.log ] && [ -f /var/log/adsb-setup.log ] && cp /var/log/adsb-setup.log /opt/adsb/adsb-setup.log
 
-exec &>> /opt/adsb/adsb-setup.log
+exec &>>/opt/adsb/adsb-setup.log
 
 trap cleanup EXIT
 
@@ -97,14 +119,19 @@ else
     git checkout "$TARGET" &> /dev/null
     git branch -D "$FAKE_BRANCH" &> /dev/null
     echo "restarting with feeder-update from $TARGET"
-    cp src/modules/adsb-feeder/filesystem/root/opt/adsb/feeder-update /opt/adsb-feeder-update/feeder-update
+    if [ ! -f src/modules/adsb-feeder/filesystem/root/opt/adsb/feeder-update ] ; then
+        echo "can't find the feeder-update app in the git tree, using existing one"
+        cp "$0" /opt/adsb-feeder-update/feeder-update
+    else
+        cp src/modules/adsb-feeder/filesystem/root/opt/adsb/feeder-update /opt/adsb-feeder-update/feeder-update
+    fi
     # add a trailing '-go' argument, and the correct target as first argument; this way the call should
     # be compatible with older versions of the script - not that anyone should want to downgrade using this script
     XTRACE="" && [[ -o xtrace ]] && XTRACE="-x"
     if [ -f /opt/adsb-feeder-update/feeder-update ] ; then
         # the cleanup trap will be re-initialized in the child script, so disable it here
         trap - EXIT
-        bash "$XTRACE" /opt/adsb-feeder-update/feeder-update "$TARGET" "$BRANCH" "$@" -go
+        bash $XTRACE /opt/adsb-feeder-update/feeder-update "$TARGET" "$BRANCH" "$@" -go
     else
         echo "can't find /opt/adsb-feeder-update/feeder-update after update to $TARGET"
     fi
