create various VM images on GitHub
Now that we are prying apart the DietPi build we can use the freshly added
--createvms option to take the raw image and continue processing; this way we
get ready to go VM images instead of just a .vmdk.

Unfortunately that makes the 'running out of space' issue even worse. So let's
try to clean  up even earlier and see if that allows us to make it all the way
through.

This also takes a step at simplifying the naming and making the upload logic
more consistent.

Signed-off-by: Dirk Hohndel <dirk@hohndel.org>

diff --git a/src/build_dist b/src/build_dist
--- a/src/build_dist
+++ b/src/build_dist
@@ -93,6 +93,18 @@ if [[ "$VARIANT" == "iob-dietpi"* ]] ; then
     cp "${DIR}/variants/iob-dietpi/Automation_Custom_Script.sh" "$MNT_DIR"/"$CONFIG_DIR"
     cp "${DIR}/modules/adsb-feeder/filesystem/root/boot/ADSB-README.txt" "$MNT_DIR"/"$CONFIG_DIR"
     unmount_image "$MNT_DIR"
+    if [[ "$VARIANT" == "iob-dietpi-root-only" && "$BASE_IMG" == *"VM"* ]] ; then
+        # now let's create all of the different VM images that DietPi knows about
+        if [[ ! -d "${DIR}/../../DietPi" ]] ; then
+            echo "DietPi not found in \${DIR}/../../"
+            ls -l "${DIR}/../../"
+            exit 0
+        fi
+        cd image-dietpi || exit 0
+        G_GITOWNER=dirkhh G_GITBRANCH=adsbim ../../../DietPi/.build/images/dietpi-build -v all   -m 20 -o dirkhh -b adsbim --createvms
+        pwd
+        ls -l
+    fi
     exit 0
 else
     VERSION=$(bash "${DIR}/get_version.sh")
